### ISSUE TITLE
Please implement 'Simulate Docking->Window focus' options for TST in separate window. 

### ISSUE THREAD

**Issue by blza** [Lej77/tree-style-tab-in-separate-window#10]
Doing so will make it super convenient to use TST window on the second monitor.

**Comment by Lej77** [comment]
Not sure what this issue is about since this setting should already be implemented. Its under `Docked Window Settings` `->` `Simulate docking` `->` `Window focus`. They should even be enabled by default. Is there a bug so they don't work correctly, do you want more/new focus functionality or maybe you aren't opening a docked window correctly (as I described in [this comment](https://github.com/Lej77/tree-style-tab-in-separate-window/issues/9#issuecomment-703174533))?

Edit: I think I get it! I guess you want to be able to use the auto window focus options even when you are not docking a window to a specific position. Is this correct?

**Comment by Lej77** [comment]
If you just wanted to enable the window focus options without controlling the window positions then that is possible with version 5.3 of the extension. The relevant setting is: `Docked Window Settings` section `->` `Open beside current window` area `->` `Simulate docking` section `->` `Control the position and size of docked sidebar windows.` checkbox. Unchecking it will prevent the code that moves the docked window from running. Note that you must still have the `Docked Window Settings` `->` `Create the new window beside the current window (will un-maximize the current window if needed).` setting enable which can be a bit annoying if you want a full maximized window but you can probably change some other settings such as window offset and width to try to make it slightly better.

**Comment by blza** [comment]
Oh, the last one was tricky, but worked. Thanks a lot! Never would I get the settings right by myself!
