### ISSUE TITLE
drag and drop not working if set to option 5 in Drag and Drop TSTs option page

### ISSUE THREAD

**Issue by N3C2L** [Lej77/tree-style-tab-in-separate-window#13]
How to reproduce:

Go to option page "Drag and Drop" in TST Settings:

Drag and Drop with your addon not working with this option: Set left side "Drag" at the 5. position: "create link or bookmark from Solo Tab if expanded or Entire Tree if collapsed (but impossible to detach from the window)". It alwys loads the page and leaves the Addon Window.

Only working with option if "Drag" is at first option "Detach Entire Tree always from the window (but impossible to create bookmarks)"

**Comment by Lej77** [comment]
Ahh, I have never used that option and so didn't notice this problem. Anyway since this addon really does very little (only opening Tree Style Tab's own sidebar page in a new tab/window) the fix will have to be made in Tree Style Tab's code.

From my testing you would need code similar to the below  ([taken from here](https://stackoverflow.com/questions/6756583/prevent-browser-from-loading-a-drag-and-dropped-file?rq=1)) in order to prevent loading of the dropped links:
```javascript
window.addEventListener("dragover", function (e) {
    e = e || event;
    e.preventDefault();
}, false);
window.addEventListener("drop", function (e) {
    e = e || event;
    e.preventDefault();
}, false);
```

The code for Tree Style Tab's sidebar does call [`preventDefault` for the `"dragover"` event](https://github.com/piroor/treestyletab/blob/b6231a9d07db8112e9a1a836b9787ad1cf7d7ee4/webextensions/sidebar/drag-and-drop.js#L1037) but it never does so for [the `"drop"` event](https://github.com/piroor/treestyletab/blob/b6231a9d07db8112e9a1a836b9787ad1cf7d7ee4/webextensions/sidebar/drag-and-drop.js#L1246). 

One reason that Tree Style Tab doesn't call `preventDefault` could be because that would also prevent actions when the items are dropped outside of the sidebar but I'm not so sure about that. Also I don't think the `"drop"` event should be triggered unless things are actually dropped on the sidebar. So maybe we should just make an issue with Tree Style Tab about calling `preventDefault` for the `"drop"` event.

**Comment by Lej77** [comment]
I have [created an issue for TST](https://github.com/piroor/treestyletab/issues/3056) so that hopefully the changes I wanted can be made to TST.

**Comment by piroor** [comment]
Thanks! TST's commit https://github.com/piroor/treestyletab/commit/f90e17e44efc45f6f8aa93db1ee2bc65164cd0bd should fix this.

**Comment by Lej77** [comment]
Wow, that was a fast fix!

**Comment by N3C2L** [comment]
Thanks a lot!
