### ISSUE TITLE
TST not opening in separate window

### ISSUE THREAD

**Issue by SamirSaidani** [Lej77/tree-style-tab-in-separate-window#5]
Step to reproduce:
- On Window 10, with FF 65.0.2 (64 bits),  TST 2.8.3, and TST in SW 3.3, all options by default
- both open on a separate window and docked window don't work

**Comment by Lej77** [comment]
Thanks for reporting this. The problem was that the method I used to detect Tree Style Tab's internal id uses Tree Style Tab's API to open a group tab. In the latest release of Tree Style Tab waiting on that command causes an infinite wait so I added a timeout and that fixed it. I release a new version of this extension (v3.4) that includes the fix so just update the extension and it should work again.
