### ISSUE TITLE
tree-style-tab-in-separate-window is not working

### ISSUE THREAD

**Issue by viking2** [Lej77/tree-style-tab-in-separate-window#6]
I also posted this issue over at TST:
https://github.com/piroor/treestyletab/issues/2617#issuecomment-647045734:

I created a new FF (v77) profile with only TST & TSTSW. 
1. When I click on the TSTSW I get a message that TST's ID cannot be determined:
![](https://i.gyazo.com/f46700d21db0e5ac3225ef500b09ed4d.png)
2. However, I have granted access in TST:
![](https://i.gyazo.com/cf6459ecff2aa5e770c3930155c60826.png)
3. I always have to force an update in TSTSW:
![](https://i.gyazo.com/8042c053dbcf08995ac3d4143cb4b8f7.png)
4. After this, I can open the TSTSW. However:
a. A separate tab is opened in TST (only) with the internal ID. Is that by design?
b. If I open new tabs in TST, they only show up in TSTSW (& FF top Tabs) but not in TST.  That is not what I had expected (I had expected the tabs to show in both TST & TSTSW):
![](https://i.gyazo.com/c41edb63d443250da546e74002fb39c2.png)

I am using WIN7(64-bit). I also installed TST & TSTSW on a different WIN7(32-bit) PC, and I had the same issues.  
Firefox: v77.0.1
TST v3.5.5
tree-style-tab-in-separate-window v4.2

UPDATE: I now tried it on a 3rd PC running WIN10(64-bit) and had the same issues.

**Comment by viking2** [comment]
I am beginning to believe that the Tabs cannot be updated both in TST and TSTSW? This is causing a lot of issues. Can this be fixed so that the Tabs are synchronized between TST and TSTSW?

Here is another example of weirdness:
1. Open FF with 1 tab and TST closed
2. Open TSTSW => Shows 1 tab in TSTSW and Firefox regular tabs.
3. Add 1 tab in TSTSW => Shows 2 tabs as expected in TSTSW and Firefox regular tabs.
4. Open TST => Also shows 2 tabs as expected
5. Close TST
6. Add 1 tab in TSTSW => New Tab is not shown in TSTW (but in Firefox regular tabs which shows expected 3 tabs)!
7. Add 1 tab in Firefox => Again, the new tab is not shown in TSTSW, which still only shows 2 tabs (but Firefox now shows the expected 4 tabs)
8. Open TST => It shows the expected 4 tabs

**Comment by Lej77** [comment]
Tree Style Tab's sidebar just shows a special web page provided by Tree Style Tab. This extension simply determines that web page's URL and opens it in a tab which is then moved to a new window. When I made this extension it did indeed work as you describe (the separate window and the sidebar were both kept up to date) but changes in Tree Style Tab has since caused this new behavior. It seems that Tree Style Tab expects there to only be a single "sidebar" web page which is a reasonable expectation but it unfortunately makes the user experience with this extension a lot worse.

I can't think of a simple fix via changes to this extension (I would have to essentially re implement the sidebar page myself which seems like a lot of work). Maybe Tree Style Tab could make a simple change to allow for having several "sidebar" web pages open at once again but I have no idea how difficult that would be.

**Comment by viking2** [comment]
Are you working on fixing this extension after the TST modification?

**Comment by Lej77** [comment]
@viking2 I actually have some modifications ready but I'm waiting for Tree Style Tab to release its next version so I can do some final testing before updating the extension. I also need to wait since some of the default setting changes won't work well with older Tree Style Tab versions and I don't want the extension to stop working until Tree Style Tab updates. Releasing a new version is really quick though (usually takes less than 10min for me) so as soon as Tree Style Tab has updated I will release the update. If you see that TST has updated and I missed it then you can always make another comment on this issue!

**Comment by Lej77** [comment]
@viking2 I have released version `5.0` of this extension that includes support for Tree Style Tab's new `?windowId=3` query parameter so that the "sidebar" page can be opened directly in a new window without moving it from the current window. It also includes support for the new `ext+treestyletab:tabbar` URI that works as a shorthand for the real URI `moz-extension://xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/sidebar/sidebar.html` that depends on Tree Style Tab's internal id, this means that the extension no longer needs to determine the internal id and so the extension should just work directly after being installed!

**Comment by viking2** [comment]
With the latest TST update this also works with the right-click menus now! Thanks!
