### ISSUE TITLE
Position

### ISSUE THREAD

**Issue by wvxwxvw** [Lej77/tree-style-tab-in-separate-window#8]
How do position your window to the right of the main Firefox window?

**Comment by Lej77** [comment]
Unfortunately this feature isn't implemented yet. The code was written to always assume that the window would be opened to the left. The relevant code is [here (where the position of newly opened windows is determined)](https://github.com/Lej77/tree-style-tab-in-separate-window/blob/ef6bfa6e4ed02eedab36ee56612b01b0a55bd949/background/background.js#L420-L431), [here (where the opened window's position is double checked since it might not actually be where we wanted it to be)](https://github.com/Lej77/tree-style-tab-in-separate-window/blob/ef6bfa6e4ed02eedab36ee56612b01b0a55bd949/background/background.js#L460-L494), [here (where the position is set every second or so whenever the parent window is moved)](https://github.com/Lej77/tree-style-tab-in-separate-window/blob/ef6bfa6e4ed02eedab36ee56612b01b0a55bd949/background/simulate-docking.js#L714-L795) and possibly [here (where we try to find docked sidebar windows when the extension or browser is restarted. This code is a bit hacky though and if docked sidebar info is stored in session data then it won't even get run. So this could probably be safely ignored/skipped.)](https://github.com/Lej77/tree-style-tab-in-separate-window/blob/ef6bfa6e4ed02eedab36ee56612b01b0a55bd949/background/simulate-docking.js#L1001). So some modifications to the code in all those places would be needed. I will try to take a look at this whenever I get the time but if you want you can also make some changes and then send me a pull request.

**Comment by wvxwxvw** [comment]
@Lej77 
I will make it so that you will have to redo. Better not to start.
Better you yourself, over time.

**Comment by Lej77** [comment]
Docking the Tree Style Tab window on the right side of the parent window has been added in version 5.3 of the extension and is available as a setting on the options page. It is under the "Docked Window Settings" section in the "Open beside current window" area and is called "Open the window to the right of the main window instead of to the left".
