### ISSUE TITLE
Window title

### ISSUE THREAD

**Issue by mreppen** [Lej77/tree-style-tab-in-separate-window#9]
Hi, I'll take the opportunity to say thanks for a great plugin.

This is a feature request: The window title of the tabs window is set to simply "Mozilla Firefox". It would be great if this window title were something specific to the tabs window. Is this possible?

**Comment by Lej77** [comment]
Hi! I'm glad that you are enjoying the addon!

Regarding modifying the window's title, it should be possible. I could use the [`browser.windows.update(windowId, { titlePreface: "Tree Style Tab Sidebar" })`](https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/windows/update) API to change the title. It wouldn't even require any new permissions. The `titlePreface` is shared between extensions though so if another extension is installed that also sets the title preface (like [Tab Count in Window Title](https://addons.mozilla.org/firefox/addon/tab-count-in-window-title)) then only the last title preface that is set will be shown. It might still be worth trying though! 
Edit: Actually I think that if a tab's title is empty then the title preface won't be shown, so this might not work after all. 
Edit 2: I tested changing the title using title preface and it does work so that isn't an issue.

Another approach would be to change the sidebar tab's title. I don't think it is possible to inject javascript into extension pages so this would probably require that a tiny bit of code is added to Tree Style Tab. This shouldn't be a problem however since code to support this extension [has been added before](https://github.com/piroor/treestyletab/issues/2619). Currently this extension opens the Tree Style Tab's sidebar page by opening the URL `ext+treestyletab:tabbar?windowId=3`, I'm thinking that we could just open the URL `ext+treestyletab:tabbar?windowId=3&title=Sidebar` instead and then Tree Style Tab would read the URL and set the title. I can't think of any disadvantages for this second approach so it is the one I would prefer to implement.

**Comment by mreppen** [comment]
Thanks for the elaborate discussion. As long as the window at some point changes, it works for my needs. My window manager lets me trigger commands on encountering certain titles. With the "Mozilla Firefox" title, the tabs window is not distinguished from a regular FF window, but even a temporary title change is enough for the trigger.

So for me either of the two solutions is great, but I agree the second is more elegant. Would you like me to open an issue in the TST repo? I have not worked with FF plugins in more than 10 years, so unfortunately I am not able to help with the details.

(OT: Do you know if `userChrome.css` can remove the address/navigation bar from the tabs window only?)

**Comment by Lej77** [comment]
I could implement the first solution, it shouldn't be very hard. If you want you can open a new issue for Tree Style Tab and if/when it is possible to change the tab's title I can implement support for that as well.

Regarding `userChrome.css`, I am unsure what you are asking for. Do you want to hide the title bar of the window that is opened by this extension? If so then I am not sure if that is possible. It doesn't seem to be part of the HTML that makes up the UI. You could change the window type in this extension's option page (under `Docked Window Settings` > `Window Type` > uncheck the `Create the new window without a tab bar`) and then you could style even the title bar. That does have some other issues though, like opening a TST sidebar in that new window.

**Comment by mreppen** [comment]
As you see above, I have opened an issue in the TST repo.

Regarding the other question: the window from this extension still has the address bar and navigation buttons (back, forward), i.e., the whole bar that is normally sitting under the tabs. I would like to keep it for regular windows but for the tabs window I don't need the address bar or navigation so I would like to remove it for this window only.
![image](https://user-images.githubusercontent.com/4117518/94996472-fa60f180-0572-11eb-9656-5be40f6b0ebe.png)


It might be related to https://github.com/Lej77/tree-style-tab-in-separate-window/issues/2 which should already be implemented, but the settings I tried don't get rid of the address bar, so I was hoping for `userChrome.css`. Maybe I would better open a separate issues for this.

**Comment by Lej77** [comment]
Thank you for opening an issue with Tree Style Tab!

Regarding the sidebar page, I am using Windows 10 and my sidebar window looks like this:
![TST sidebar window](https://user-images.githubusercontent.com/31554212/94997522-074e0700-05ac-11eb-805e-46430bbeccd6.png)

The window should be created as a [`popup`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows/CreateType) type so Firefox shouldn't show the address bar. How does it look when Tree Style Tab opens its "Close tabs?" popup (it does this whenever you try to close a lot of tabs at the same time)?. You could try to change the type of the created window in the extension's option page (under `Docked Window Settings` > `Window Type`).

Still, if that doesn't work then it should indeed be possible to hide most of that UI using CSS. The description for [Tab Count in Window Title](https://addons.mozilla.org/firefox/addon/tab-count-in-window-title/) mentions that you can access title prefaces with `userChrome.css` so you could use a unique title preface for those windows to apply some custom style rules. So if "popup" windows don't have any unique classes or attributes then it should still be possible to write CSS that is specific for those windows.

**Comment by mreppen** [comment]
I have tried to toggle both checkboxes in the `Window Type` settings, but neither seems to make a difference. I also tried to remove my `userChrome.css` to see if that was spooking, but no difference.

Closing multiple tabs:
![image](https://user-images.githubusercontent.com/4117518/94999711-43bc3b80-0589-11eb-976c-9d14ca87efea.png)
(this seems more like an "alert" window than a "popup", as popups typically have non-chrome content)

FWIW, I am on Linux (Wayland). But Firefox "popup" windows work in normal contexts (for website popups) so it's not that the window type is missing on Linux.

I tried it on a Windows computer now and there it works as for you. Odd

**Comment by Lej77** [comment]
The `window type` setting only affects windows that are opened using the `docked window` command so make sure you are actually opening a window that way.
There are a couple of ways to invoke that command:
1. Configure your default command to be opening a docked window:
![TST separate window - Settings - Sidebar page location](https://user-images.githubusercontent.com/31554212/95003074-958db180-05db-11eb-90aa-e82eed4f429b.png)
2. Change the default command to a docked window by right clicking the extension's toolbar icon and using the context menu:
![TST separate window - Settings - Change default action context menu](https://user-images.githubusercontent.com/31554212/95003121-12b92680-05dc-11eb-95a2-56920bbe0a08.png)
3. Open a docked window via the toolbar button's context menu:
![TST separate window - Settings - Docked window context menu](https://user-images.githubusercontent.com/31554212/95003125-1482ea00-05dc-11eb-8def-8bb57f45d66d.png)
4. Set a keyboard shortcut for the `Open Tree Style Tab Sidebar in a docked window` command and use that.

## More info about window type

I though I would clarify what the `Window type` options actually do. It changes how the extension creates new windows. That means that windows that were previously opened by the extension are unaffected if the options are changed. Created windows can be of [4 types](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows/CreateType) (`normal`, `popup`, `panel` and `detached_panel`). The [`browser.windows.create` API docs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/windows/create) has some more info about the different types. From my testing it seems that there  is really only 2 types `normal` and `popup`, the other types seem to behave the same as `popup`. But when I made the extension I thought `panel` would be more private than `popup` and hide the new window from other extensions so that is why the options page has the description it does.

`normal` window type:

![TST separate window - Settings - Normal](https://user-images.githubusercontent.com/31554212/95002852-e6e87180-05d8-11eb-8f81-619fe856bc65.png)

`popup` window type:

![TST separate window - Settings - Popup](https://user-images.githubusercontent.com/31554212/95002855-e9e36200-05d8-11eb-9832-484741493baf.png)

`panel` window type:

![TST separate window - Settings - Panel](https://user-images.githubusercontent.com/31554212/95002853-e8199e80-05d8-11eb-8041-48a6bdbe1ff8.png)

Some code locations:
[Here is where the global settings' default values are defined](https://github.com/Lej77/tree-style-tab-in-separate-window/blob/ef6bfa6e4ed02eedab36ee56612b01b0a55bd949/common/common.js#L94-L98).
[Here the global settings are read and copied into a temporary object](https://github.com/Lej77/tree-style-tab-in-separate-window/blob/ef6bfa6e4ed02eedab36ee56612b01b0a55bd949/background/background.js#L690).
[Here the type of the created window is decided based on properties of the temporary object](https://github.com/Lej77/tree-style-tab-in-separate-window/blob/ef6bfa6e4ed02eedab36ee56612b01b0a55bd949/background/background.js#L402).
[Here the new window is created with the info that was specified previously](https://github.com/Lej77/tree-style-tab-in-separate-window/blob/ef6bfa6e4ed02eedab36ee56612b01b0a55bd949/background/background.js#L438).

**Comment by Lej77** [comment]
I released a small update of the extension (`v5.1`) that now sets a title preface for created "docked" windows.

**Comment by Lej77** [comment]
I released another update of the extension (`v5.2`) that uses the new `title` URL parameter to set the title of created sidebar pages. I changed the default settings to not set a window title preface anymore since the tab title should be used as window title anyway and probably be more useful overall (things like: it can't be overridden by other addons, is visible even when the page is opened as a tab). Still the title preface setting is still there and available if you want to use it for some CSS rules with `userChrome.css`.

**Comment by mreppen** [comment]
> The window type setting only affects windows that are opened using the docked window command so make sure you are actually opening a window that way.

That was it. I had set up key bindings and forgot that they are specific to docked/not docked. Thanks for the clarification.

On one of my devices, the TST window refuses to scroll if I resize it even the slightest. I suspect it is related to the window trying to set a minimum width and thinks it is as large as Firefox itself, which it is not. Unticking the main box in `Open beside current window` seems to solve it for me. Leaving this here in case somebody encounters a similar issue.

My window rules are working and I am really happy how it turned out. Thanks again!
